eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-server:8761/eureka # for docker
  instance:
    hostname: ${spring.application.name}
